const colors = {
  light: {
    text: "#1a1a2e",
    tint: "#6c63ff",
    background: "#f8f7ff",
    foreground: "#1a1a2e",
    card: "#ffffff",
    cardForeground: "#1a1a2e",
    primary: "#6c63ff",
    primaryForeground: "#ffffff",
    secondary: "#ede9fe",
    secondaryForeground: "#4c1d95",
    muted: "#f3f4f6",
    mutedForeground: "#9ca3af",
    accent: "#a78bfa",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e7eb",
    input: "#e5e7eb",
    success: "#10b981",
    successLight: "#d1fae5",
    warning: "#f59e0b",
    warningLight: "#fef3c7",
    gridDone: "#6c63ff",
    gridEmpty: "#ede9fe",
    gridFuture: "#f3f4f6",
    streakOrange: "#f97316",
  },
  dark: {
    text: "#f1f0ff",
    tint: "#a78bfa",
    background: "#0f0e1a",
    foreground: "#f1f0ff",
    card: "#1a1933",
    cardForeground: "#f1f0ff",
    primary: "#7c6ffd",
    primaryForeground: "#ffffff",
    secondary: "#2d2a5e",
    secondaryForeground: "#c4b5fd",
    muted: "#1e1d35",
    mutedForeground: "#6b7280",
    accent: "#7c6ffd",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2d2a5e",
    input: "#2d2a5e",
    success: "#10b981",
    successLight: "#064e3b",
    warning: "#f59e0b",
    warningLight: "#451a03",
    gridDone: "#7c6ffd",
    gridEmpty: "#2d2a5e",
    gridFuture: "#1e1d35",
    streakOrange: "#f97316",
  },
  radius: 14,
};

export default colors;
